### ISSUE TITLE
Tensorflow error in M5_TrainModel.py

### ISSUE THREAD

**Issue by antonioiuliano2** [FilipsFedotovs/EDER-VIANN#31]
Dear Filips,

unfortunately the HTCondor job in M5_TrainModel.py immediately fails, with the following error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "/afs/cern.ch/work/a/aiuliano/public/Filips_MachineLearning/EDER-VIANN/Code/Utilities/M5_TrainModel_Sub.py", line 24, in <module>
    from keras.models import Sequential
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/utils/__init__.py", line 26, in <module>
    from .vis_utils import model_to_dot
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/utils/vis_utils.py", line 7, in <module>
    from ..models import Model
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/models.py", line 10, in <module>
    from .engine.input_layer import Input
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/engine/__init__.py", line 3, in <module>
    from .input_layer import Input
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/engine/input_layer.py", line 7, in <module>
    from .base_layer import Layer
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 12, in <module>
    from .. import initializers
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/initializers/__init__.py", line 22, in <module>
    from keras.initializers import initializers_v1
  File "/afs/cern.ch/user/a/aiuliano/.local/lib/python3.6/site-packages/keras/initializers/initializers_v1.py", line 21, in <module>
    _v1_zeros_initializer = tf.compat.v1.zeros_initializer
AttributeError: module 'tensorflow._api.v1.compat.v2.compat' has no attribute 'v1'

Any idea what is happening?
Best regards,
Antonio

**Comment by antonioiuliano2** [comment]
Found solution, conflict between keras-2.3.1 and keras-nightly.
Remove them both:

```
pip3 uninstall keras-nightly 
pip3 uninstall keras-2.3.1
```

Then reinstall:

`pip3 install keras-2.3.1 --user `
